In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import random
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, tree
import xgboost
from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import plot_tree
import seaborn as sns
import xlwt
from xlwt import Workbook
from sklearn.preprocessing import OneHotEncoder
from sklearn import preprocessing
from sklearn import datasets, linear_model, metrics
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, tree
import xgboost
import csv
from scipy import sparse
from sklearn.naive_bayes import BernoulliNB
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from numpy import count_nonzero

In [2]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import random
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [3]:
df = pd.read_csv("dataset/train.csv")

In [4]:
df = df.drop("qa_id",axis=1)
df.head()

question_title  \
0  What am I losing when using extension tubes in...   
1  What is the distinction between a city and a s...   
2  Maximum protusion length for through-hole comp...   
3              Can an affidavit be used in Beit Din?   
4       How do you make a binary image in Photoshop?   

                                       question_body question_user_name  \
0  After playing around with macro photography on...               ysap   
1  I am trying to understand what kinds of places...      russellpierce   
2  I'm working on a PCB that has through-hole com...          Joe Baker   
3  An affidavit, from what i understand, is basic...         Scimonster   
4  I am trying to make a binary image. I want mor...            leigero   

                                  question_user_page  \
0         https://photo.stackexchange.com/users/1024   
1           https://rpg.stackexchange.com/users/8774   
2  https://electronics.stackexchange.com/users/10157   
3       https://judaism.stackexchange.com/users/5151   
4  https://graphicdesign.stackexchange.com/users/...   

                                              answer answer_user_name  \
0  I just got extension tubes, so here's the skin...           rfusca   
1  It might be helpful to look into the definitio...     Erik Schmidt   
2  Do you even need grooves?  We make several pro...      Dwayne Reid   
3  Sending an "affidavit" it is a dispute between...    Y     e     z   
4  Check out Image Trace in Adobe Illustrator. \n...             q2ra   

                                    answer_user_page  \
0         https://photo.stackexchange.com/users/1917   
1           https://rpg.stackexchange.com/users/1871   
2  https://electronics.stackexchange.com/users/64754   
3       https://judaism.stackexchange.com/users/4794   
4  https://graphicdesign.stackexchange.com/users/...   

                                                 url   category  \
0  http://photo.stackexchange.com/questions/9169/...  LIFE_ARTS   
1  http://rpg.stackexchange.com/questions/47820/w...    CULTURE   
2  http://electronics.stackexchange.com/questions...    SCIENCE   
3  http://judaism.stackexchange.com/questions/551...    CULTURE   
4  http://graphicdesign.stackexchange.com/questio...  LIFE_ARTS   

                              host  ...  question_well_written  \
0          photo.stackexchange.com  ...               1.000000   
1            rpg.stackexchange.com  ...               0.888889   
2    electronics.stackexchange.com  ...               0.777778   
3        judaism.stackexchange.com  ...               0.888889   
4  graphicdesign.stackexchange.com  ...               1.000000   

   answer_helpful  answer_level_of_information  answer_plausible  \
0        1.000000                     0.666667          1.000000   
1        0.888889                     0.555556          0.888889   
2        0.777778                     0.555556          1.000000   
3        0.833333                     0.333333          0.833333   
4        1.000000                     0.666667          1.000000   

   answer_relevance  answer_satisfaction  answer_type_instructions  \
0          1.000000             0.800000                       1.0   
1          0.888889             0.666667                       0.0   
2          1.000000             0.666667                       0.0   
3          1.000000             0.800000                       0.0   
4          1.000000             0.800000                       1.0   

   answer_type_procedure  answer_type_reason_explanation  answer_well_written  
0               0.000000                        0.000000             1.000000  
1               0.000000                        0.666667             0.888889  
2               0.333333                        1.000000             0.888889  
3               0.000000                        1.000000             1.000000  
4               0.000000                        1.000000             1.000000  

[5 rows x 40 columns]

In [5]:
df = df.drop("question_user_name",axis=1)
df = df.drop("answer_user_name",axis=1)

In [6]:
all_col = []

In [7]:
for i in df.columns:
    all_col.append(i)

In [8]:
print(all_col)

['question_title', 'question_body', 'question_user_page', 'answer', 'answer_user_page', 'url', 'category', 'host', 'question_asker_intent_understanding', 'question_body_critical', 'question_conversational', 'question_expect_short_answer', 'question_fact_seeking', 'question_has_commonly_accepted_answer', 'question_interestingness_others', 'question_interestingness_self', 'question_multi_intent', 'question_not_really_a_question', 'question_opinion_seeking', 'question_type_choice', 'question_type_compare', 'question_type_consequence', 'question_type_definition', 'question_type_entity', 'question_type_instructions', 'question_type_procedure', 'question_type_reason_explanation', 'question_type_spelling', 'question_well_written', 'answer_helpful', 'answer_level_of_information', 'answer_plausible', 'answer_relevance', 'answer_satisfaction', 'answer_type_instructions', 'answer_type_procedure', 'answer_type_reason_explanation', 'answer_well_written']


In [9]:
print(len(all_col))

38


In [10]:
def check_null(daf,col):
    count = 0
    x = daf[col].isnull()
    arr = x.values.tolist()
    for i in arr:
        if(i):
            count+=1
    if(count>=0):
        print("The length of the {} is {} and null values are {} and datatype is {}".format(col,str(len(arr)),str(count),daf[col].dtypes ))


In [11]:
for i in df.columns:
    check_null(df,i)

The length of the question_title is 6079 and null values are 0 and datatype is object
The length of the question_body is 6079 and null values are 0 and datatype is object
The length of the question_user_page is 6079 and null values are 0 and datatype is object
The length of the answer is 6079 and null values are 0 and datatype is object
The length of the answer_user_page is 6079 and null values are 0 and datatype is object
The length of the url is 6079 and null values are 0 and datatype is object
The length of the category is 6079 and null values are 0 and datatype is object
The length of the host is 6079 and null values are 0 and datatype is object
The length of the question_asker_intent_understanding is 6079 and null values are 0 and datatype is float64
The length of the question_body_critical is 6079 and null values are 0 and datatype is float64
The length of the question_conversational is 6079 and null values are 0 and datatype is float64
The length of the question_expect_short_ans

In [12]:
train_label =[]
ans_label = []

In [13]:
train_label = all_col[0:8]

In [14]:
print(train_label)

['question_title', 'question_body', 'question_user_page', 'answer', 'answer_user_page', 'url', 'category', 'host']


In [15]:
ans_label = all_col[8:]

In [16]:
print(ans_label)

['question_asker_intent_understanding', 'question_body_critical', 'question_conversational', 'question_expect_short_answer', 'question_fact_seeking', 'question_has_commonly_accepted_answer', 'question_interestingness_others', 'question_interestingness_self', 'question_multi_intent', 'question_not_really_a_question', 'question_opinion_seeking', 'question_type_choice', 'question_type_compare', 'question_type_consequence', 'question_type_definition', 'question_type_entity', 'question_type_instructions', 'question_type_procedure', 'question_type_reason_explanation', 'question_type_spelling', 'question_well_written', 'answer_helpful', 'answer_level_of_information', 'answer_plausible', 'answer_relevance', 'answer_satisfaction', 'answer_type_instructions', 'answer_type_procedure', 'answer_type_reason_explanation', 'answer_well_written']


In [17]:
print(len(train_label))
print(len(ans_label))

8
30


In [18]:
def string_to_feature(df,col):
    corpus = []
    for i in df[col]:
        corpus.append(i)
        
    vectorizer = TfidfVectorizer(min_df=1,stop_words="english")
    corpus = vectorizer.fit_transform(corpus).toarray()
    return corpus
    

In [19]:
for col in train_label:
    df[col] = string_to_feature(df,col)

In [20]:
df.shape

(6079, 38)

In [21]:
dataset = df.values

In [22]:
X = dataset[:,0:8]
# y = dataset[:,8:]

In [23]:
for col in train_label:
    check_null(df,col)

The length of the question_title is 6079 and null values are 0 and datatype is float64
The length of the question_body is 6079 and null values are 0 and datatype is float64
The length of the question_user_page is 6079 and null values are 0 and datatype is float64
The length of the answer is 6079 and null values are 0 and datatype is float64
The length of the answer_user_page is 6079 and null values are 0 and datatype is float64
The length of the url is 6079 and null values are 0 and datatype is float64
The length of the category is 6079 and null values are 0 and datatype is float64
The length of the host is 6079 and null values are 0 and datatype is float64


In [24]:
print(X.shape)
print(type(X[0][0]))

(6079, 8)
<class 'numpy.float64'>


In [25]:
print(X.shape)

(6079, 8)


In [26]:
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [27]:
answer = []

In [28]:
test = pd.read_csv("dataset/test.csv")

In [29]:
test.head()

qa_id                                     question_title  \
0     39  Will leaving corpses lying around upset my pri...   
1     46         Url link to feature image in the portfolio   
2     70  Is accuracy, recoil or bullet spread affected ...   
3    132     Suddenly got an I/O error from my external HDD   
4    200  Passenger Name - Flight Booking Passenger only...   

                                       question_body question_user_name  \
0  I see questions/information online about how t...              Dylan   
1  I am new to Wordpress. i have issue with Featu...                Anu   
2  To experiment I started a bot game, toggled in...             Konsta   
3  I have used my Raspberry Pi as a torrent-serve...           robbannn   
4  I have bought Delhi-London return flights for ...               Amit   

                                  question_user_page  \
0       https://gaming.stackexchange.com/users/64471   
1    https://wordpress.stackexchange.com/users/72927   
2       https://gaming.stackexchange.com/users/37545   
3  https://raspberrypi.stackexchange.com/users/17341   
4       https://travel.stackexchange.com/users/29089   

                                              answer answer_user_name  \
0  There is no consequence for leaving corpses an...        Nelson868   
1  I think it is possible with custom fields.\n\n...            Irina   
2  You do not have armour in the screenshots. Thi...   Damon Smithies   
3  Your Western Digital hard drive is disappearin...      HeatfanJohn   
4  I called two persons who work for Saudia (tick...    Nean Der Thal   

                                   answer_user_page  \
0      https://gaming.stackexchange.com/users/97324   
1   https://wordpress.stackexchange.com/users/27233   
2      https://gaming.stackexchange.com/users/70641   
3  https://raspberrypi.stackexchange.com/users/1311   
4      https://travel.stackexchange.com/users/10051   

                                                 url    category  \
0  http://gaming.stackexchange.com/questions/1979...     CULTURE   
1  http://wordpress.stackexchange.com/questions/1...  TECHNOLOGY   
2  http://gaming.stackexchange.com/questions/2154...     CULTURE   
3  http://raspberrypi.stackexchange.com/questions...  TECHNOLOGY   
4  http://travel.stackexchange.com/questions/4704...     CULTURE   

                            host  
0       gaming.stackexchange.com  
1    wordpress.stackexchange.com  
2       gaming.stackexchange.com  
3  raspberrypi.stackexchange.com  
4       travel.stackexchange.com

In [30]:
test = test.drop("qa_id",axis=1)
test = test.drop("question_user_name",axis=1)
test = test.drop("answer_user_name",axis=1)

In [31]:
test.head()

question_title  \
0  Will leaving corpses lying around upset my pri...   
1         Url link to feature image in the portfolio   
2  Is accuracy, recoil or bullet spread affected ...   
3     Suddenly got an I/O error from my external HDD   
4  Passenger Name - Flight Booking Passenger only...   

                                       question_body  \
0  I see questions/information online about how t...   
1  I am new to Wordpress. i have issue with Featu...   
2  To experiment I started a bot game, toggled in...   
3  I have used my Raspberry Pi as a torrent-serve...   
4  I have bought Delhi-London return flights for ...   

                                  question_user_page  \
0       https://gaming.stackexchange.com/users/64471   
1    https://wordpress.stackexchange.com/users/72927   
2       https://gaming.stackexchange.com/users/37545   
3  https://raspberrypi.stackexchange.com/users/17341   
4       https://travel.stackexchange.com/users/29089   

                                              answer  \
0  There is no consequence for leaving corpses an...   
1  I think it is possible with custom fields.\n\n...   
2  You do not have armour in the screenshots. Thi...   
3  Your Western Digital hard drive is disappearin...   
4  I called two persons who work for Saudia (tick...   

                                   answer_user_page  \
0      https://gaming.stackexchange.com/users/97324   
1   https://wordpress.stackexchange.com/users/27233   
2      https://gaming.stackexchange.com/users/70641   
3  https://raspberrypi.stackexchange.com/users/1311   
4      https://travel.stackexchange.com/users/10051   

                                                 url    category  \
0  http://gaming.stackexchange.com/questions/1979...     CULTURE   
1  http://wordpress.stackexchange.com/questions/1...  TECHNOLOGY   
2  http://gaming.stackexchange.com/questions/2154...     CULTURE   
3  http://raspberrypi.stackexchange.com/questions...  TECHNOLOGY   
4  http://travel.stackexchange.com/questions/4704...     CULTURE   

                            host  
0       gaming.stackexchange.com  
1    wordpress.stackexchange.com  
2       gaming.stackexchange.com  
3  raspberrypi.stackexchange.com  
4       travel.stackexchange.com

In [32]:
for col in test.columns:
    test[col] = string_to_feature(test,col)

In [33]:
test.head()

question_title  question_body  question_user_page  answer  \
0             0.0       0.000000                 0.0     0.0   
1             0.0       0.000000                 0.0     0.0   
2             0.0       0.000000                 0.0     0.0   
3             0.0       0.080418                 0.0     0.0   
4             0.0       0.000000                 0.0     0.0   

   answer_user_page  url  category  host  
0          0.000000  0.0       1.0   0.0  
1          0.000000  0.0       0.0   0.0  
2          0.000000  0.0       1.0   0.0  
3          0.000000  0.0       0.0   0.0  
4          0.721836  0.0       1.0   0.0

In [34]:
test = test.values

In [35]:
test = test[:,0:8]

In [36]:
row = 1
colo = 1
wb = Workbook()
sheet1 = wb.add_sheet('answer') 

In [37]:
count = 0
for col in df.columns:
    ans1 = []
    count+=1
    if(count>=9):
        y = df[col]
        print(col)
        model = xgboost.XGBClassifier()
        model.fit(X,y)
        y_pred= model.predict(test)
        y_pred = np.array(y_pred)
        
        sheet1.write(0,colo,col)
        
        for i in y_pred:
            sheet1.write(row,colo,i)
            row = row+1
            

        row = 1
        colo = colo+1

        wb.save('Answer.xls')
        
        

question_asker_intent_understanding
question_body_critical
question_conversational
question_expect_short_answer
question_fact_seeking
question_has_commonly_accepted_answer
question_interestingness_others
question_interestingness_self
question_multi_intent
question_not_really_a_question
question_opinion_seeking
question_type_choice
question_type_compare
question_type_consequence
question_type_definition
question_type_entity
question_type_instructions
question_type_procedure
question_type_reason_explanation
question_type_spelling
question_well_written
answer_helpful
answer_level_of_information
answer_plausible
answer_relevance
answer_satisfaction
answer_type_instructions
answer_type_procedure
answer_type_reason_explanation
answer_well_written
